export const dummy = () => ({ type: 'DUMMY' })
export const subscribeSysInfo = () => ({ type: 'SUBSCRIBE_SYS_INFO' })
export const receiveSysInfo = info => ({ type: 'RECEIVE_SYS_INFO', payload: { info } })
export const loginMyInfo = userName => ({ type: 'LOGIN_MY_INFO', payload: { userName } })
export const subscribeMyInfo = () => ({ type: 'SUBSCRIBE_MY_INFO' })
export const receiveMyInfo = info => ({ type: 'RECEIVE_MY_INFO', payload: { info } })
export const startBroadcast = url => ({ type: 'START_BROADCAST', payload: { url } })
export const endBroadcast = () => ({ type: 'END_BROADCAST' })
export const subscribeChat = () => ({ type: 'SUBSCRIBE_CHAT' })
export const clearChat = chat => ({ type: 'CLEAR_CHAT' })
export const receiveChat = chat => ({ type: 'RECEIVE_CHAT', payload: { chat } })
export const changeChatInput = text => ({ type: 'CHANGE_CHAT_INPUT', payload: { text } })
export const submitChat = (name, text, color, effect) => ({ type: 'SUBMIT_CHAT', payload: { name, text, color, effect } })
export const closeModal = () => ({ type: 'CLOSE_MODAL' })
export const showStickerModal = () => ({ type: 'SHOW_STICKER_MODAL' })
export const showVoteModal = () => ({ type: 'SHOW_VOTE_MODAL' })
export const showMyInfoModal = () => ({ type: 'SHOW_MY_INFO_MODAL' })
export const showNoticeModal = () => ({ type: 'SHOW_NOTICE_MODAL' })
export const showRankModal = () => ({ type: 'SHOW_RANK_MODAL' })
export const subscribeVote = () => ({ type: 'SUBSCRIBE_VOTE' })
export const receiveVote = vote => ({ type: 'RECEIVE_VOTE', payload: { vote } })
export const startVote = optionCount => ({ type: 'START_VOTE', payload: { optionCount } })
export const sendVote = addVote => ({ type: 'SEND_VOTE', payload: { addVote } })
export const setMyColor = color => ({ type: 'SET_MY_COLOR', payload: { color } })
export const setMyLastWatched = () => ({ type: 'SET_MY_LAST_WATCHED' })
export const toggleView = () => ({ type: 'TOGGLE_VIEW' })
export const subscribeRank = () => ({ type: 'SUBSCRIBE_RANK' })
export const receiveRank = rank => ({ type: 'RECEIVE_RANK', payload: { rank } })